# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Lokalne lokalne Unix socket (psql wewnatrz kontenera)
local   all             all                                     scram-sha-256

# poloczenia z localhost wewnatrz kontenera
host    all             all             127.0.0.1/32            scram-sha-256

# Poloczenia z sieci Dockerowej (pgAdmin, FastAPI)
host    all             all             172.16.0.0/12           scram-sha-256

# Jawny reject wszystkiego innego
host    all             all             0.0.0.0/0               reject
